
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: "科技聚变"
description: "《科技聚变》是一档科技主题播客节目，我们谈论有关互联网的一切。您可以访问 TechFusionFM.com 来找到我们，同时您也可以关注我们的 Twitter, Instagram 或微博 @TechFusionFM 。"
author: "TechFusionFM.com"
keywords: Technology, Tech, China, TechFusionFM, TechFusion, Tech Fusion, 科技播客, 科技, 互联网, IT, 播客, 科技聚变, 聚变, kejijubian, kejijvbian, keji
language: zh-CN
timezone: America/New_York

#Podcast
podcasts:
- feed:
    path: podcast.xml # relative to site root 
    title: 科技聚变
    subtitle: 《科技聚变》是一档科技主题播客节目，我们谈论有关互联网的一切。您可以访问 TechFusionFM.com 来找到我们，同时您也可以关注我们的 Twitter, Instagram 或微博 @TechFusionFM 。
    image: images/logo@2x.png # relative to config.url + config.root 
    tag: podcast # see below for tag-based feed 
    content_encoded: true # same as above, but includes the complete encoded text of the post; see note below
    copyright: "TechFusionFM.com"
    media_base_url: https://TechFusionFM.com/
    itunes:
      summary: 《科技聚变》是一档科技主题播客节目，我们谈论有关互联网的一切。
      author: TechFusionFM.com # defaults to config.author 
      owner: TechFusionFM.com
      email: hi@TchFusionFM.com # e-mail from which iTunes podcast is registered 
      tags: Technology # the category from iTunes; make sure to use their values 
      subtags: Tech News # same as above 
      explicit: clean # valid values are yes, no, and clean 
      language: zh-cn
- feed:
    path: spotlight.xml # relative to site root 
    title: 《聚焦》(《科技聚变》出品）
    subtitle: 《聚焦》是《科技聚变》的特别节目，我们聊且只聊一件事。您可以访问 TechFusionFM.com 来找到我们，同时您也可以关注我们的 Twitter, Instagram 或微博 @TechFusionFM 。
    image: images/spotlight.png # relative to config.url + config.root 
    category: spotlight # see above for category-based feed 
    content_encoded: true # same as above, but includes the complete encoded text of the post; see note below 
    copyright: "TechFusionFM.com"
    media_base_url: https://TechFusionFM.com/
    itunes:
      summary: 《聚焦》是《科技聚变》的新闻主题特别节目，我们只聊一件事。
      author: TechFusionFM.com # defaults to config.author 
      owner: TechFusionFM.com 
      email: hi@TechFusionFM.com # e-mail from which iTunes podcast is registered 
      tags: Technology # the category from iTunes; make sure to use their values 
      subtags: Tech News # same as above 
      explicit: clean # valid values are yes, no, and clean 
      language: zh-cn
- feed:
    path: gadgets.xml # relative to site root 
    title: 《小玩意儿》(《科技聚变》出品）
    subtitle: 《小玩意儿》是《科技聚变》的消费主义特别节目，我们聊新奇的一切。您可以访问 TechFusionFM.com 来找到我们，同时您也可以关注我们的 Twitter, Instagram 或微博 @TechFusionFM 。
    image: images/gadgets.png # relative to config.url + config.root 
    category: gadgets # see below for tag-based feed 
    content_encoded: true # same as above, but includes the complete encoded text of the post; see note below 
    copyright: "TechFusionFM.com"
    media_base_url: https://TechFusionFM.com/
    itunes:
      summary: 《小玩意儿》是《科技聚变》的消费主义特别节目，我们聊新奇的一切。
      author: TechFusionFM.com # defaults to config.author 
      owner: TechFusionFM.com
      email: hi@TechFusionFM.com # e-mail from which iTunes podcast is registered 
      tags: Technology # the category from iTunes; make sure to use their values 
      subtags: Gadgets # same as above 
      explicit: clean # valid values are yes, no, and clean 
      language: zh-cn

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://TechFusionFM.com
root: /
permalink: :title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: false
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Category & Tag
default_tags: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 0
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: anatole
# theme: Daily

archive_generator:
  per_page: 0
  yearly: false
  monthly: false
  daily: false

html_minifier:
  enable: true
  exclude: 

css_minifier:
  enable: true
  exclude: 
    - '*.min.css'

js_minifier:
  enable: true
  mangle: true
  output:
  compress:
  exclude: 
    - '*.min.js'

image_minifier:
  enable: true
  interlaced: false
  multipass: false
  optimizationLevel: 2
  pngquant: false
  progressive: false

robotstxt:
  useragent: "*"
  disallow:
  allow:
  sitemap: /sitemap.xml 

index_generator:
  per_page: 0
  order_by: -date
  include:
    - tag podcast # podcast only on the front page
#  exclude:
#    - tag Hexo # excluding hexp

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type:


